# Generated by Django 4.1 on 2022-09-01 03:28

import datetimeutc.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_review_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='createdBy',
        ),
        migrations.AlterField(
            model_name='order',
            name='createdAt',
            field=datetimeutc.fields.DateTimeUTCField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='paidAt',
            field=datetimeutc.fields.DateTimeUTCField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='updateAt',
            field=datetimeutc.fields.DateTimeUTCField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/images/null.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Name of the product', max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='createdAt',
            field=datetimeutc.fields.DateTimeUTCField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='updateAt',
            field=datetimeutc.fields.DateTimeUTCField(auto_now=True),
        ),
    ]
